# kind: pipeline
# name: amd
#
# platform:
#   os: linux
#   arch: amd64
#
# steps:
# - name: build
#   image: golang
#   commands:
#   - go build
#   - go test
#
# ---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: d1plo1d/teg
  environment:
    SNAPCRAFT_LOGIN:
      from_secret: snapcraft.login
  commands:
  - echo $SNAPCRAFT_LOGIN > snapcraft.login
  - snapcraft login --with snapcraft.login
  - npm install -g yarn
  - yarn install-all
  - yarn snap:push
